* https://www.youtube.com/watch?v=FAposp6k-lA&list=PLyzHIYrZBplo3K0dNUqppd2ynnoZPD6N1&index=2
* https://numpy.org/doc/stable/user/quickstart.html

We need arrays, i.e. **contiguous memory allocation** (Python provides list which is implemented by Doubly Linked List)<br/>
Getting to an index in constant time in Python. 

Every **iterable** object isn't **indexable**. Eg. a bag, list <br/>
Not every object is **mutable** i.e. value can't be modified.

In [7]:
a = 6

In the above like 'a' in the stack, is pointing to 6 in the heap memory

In [8]:
a = 8

Now you are pointing to 8 in heap memory, but you didn't change 6 in the heap memory, you are just referencing a new number.

In [1]:
import numpy as np

In [2]:
l = [14, 9, 23, 3, 4] #iterable object

In [3]:
type(l) #of type list

list

In [4]:
n_arr = np.array(l) #creating a numpy array with the list (any iterable)

In [5]:
n_arr

array([14,  9, 23,  3,  4])

In [11]:
n_arr[2] #random access

23

In [6]:
type(n_arr) #numpy's n-dimensional array

numpy.ndarray

In [9]:
np.array({2,4,3}) #creating with a set, it added like a single item tho

array({2, 3, 4}, dtype=object)

In [10]:
np.array({'a':'A', 'b':'B', 'c':'C'}) #creating with a dict, it added like a single item tho

array({'a': 'A', 'b': 'B', 'c': 'C'}, dtype=object)

In [13]:
np.array([[2,3],[4,5]])

array([[2, 3],
       [4, 5]])

In [14]:
np.array([[2,3],[4,5,6]])

array([list([2, 3]), list([4, 5, 6])], dtype=object)

In [17]:
np.array([[2,3,6,'77']]) #This makes it of type unicode

array([['2', '3', '6', '77']], dtype='<U21')

In [18]:
np.array([[2,3],[4,5]]).shape

(2, 2)

In [24]:
np.array([[2,3],[4,5]]).size

4

In [19]:
np.array([[2,3],[4,5,6]]).shape

(2,)

In [20]:
np.array([[2,3],[4,5,6]]).size

2

In [22]:
np.array([[2,3,6,'77']]).size

4

In [23]:
np.array([[2,3,6,'77']]).shape

(1, 4)

In [30]:
a = np.arange(14)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [31]:
b = np.arange(3, 17, 2)
b

array([ 3,  5,  7,  9, 11, 13, 15])

In [33]:
c = np.array(range(14))
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [34]:
a is c #Internal reference difference, to be confirmed

False

In [35]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [36]:
d = c.reshape(7,2)

In [37]:
d

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [38]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

Notice how changing d[0] changed c[0] (the stackand heap memory thing explained above)

In [39]:
d[0]=100

In [40]:
c[0]

100

In [41]:
c<20

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [43]:
c.dtype

dtype('int64')

In [44]:
c.dtype.name

'int64'

In [46]:
np.sqrt(c)

array([10.        , 10.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128])